#!/usr/bin/env php
<?php

use Illuminate\\Contracts\\Console\\Kernel as ConsoleKernelContract;
use Symfony\\Component\\Console\\Input\\ArgvInput;
use Symfony\\Component\\Console\\Output\\ConsoleOutput;

require __DIR__ . '/vendor/autoload.php';

$app = require_once __DIR__ . '/bootstrap/app.php';

$kernel = $app->make(ConsoleKernelContract::class);

$status = $kernel->handle(
    $input = new ArgvInput,
    new ConsoleOutput
);

$kernel->terminate($input, $status);

exit($status);
